[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = "0.2.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
